//
//  GLConstants.h
//  MentalGame
//
//  Created by Sergey Alpeev on 05.10.13.
//  Copyright (c) 2013 Sergey Alpeev. All rights reserved.
//

#pragma once



enum GLSL_BUFFER
{
    GLSL_ARRAY_BUFFER,
    GLSL_ELEMENT_ARRAY_BUFFER
};

enum GLSL_BUFFER_USAGE
{
    GLSL_BUFFER_USAGE_NONE,
    GLSL_BUFFER_USAGE_STREAM_DRAW,
    GLSL_BUFFER_USAGE_STATIC_DRAW,
    GLSL_BUFFER_USAGE_DYNAMIC_DRAW
};

enum GLSL_SHADER_TYPE
{
    GLSL_SHADER_TYPE_NONE,
    GLSL_SHADER_TYPE_VERTEX,
    GLSL_SHADER_TYPE_FRAGMENT
};

enum GLSL_GET_PARAMETER
{
    // TODO: New values should be added
    GLSL_GET_PARAMETER_ARRAY_BUFFER_BINDING,
    GLSL_GET_PARAMETER_ELEMENT_ARRAY_BUFFER_BINDING
};

enum GLSL_DATA_TYPE
{
    // TODO: New values should be added
    GLSL_DATA_TYPE_BYTE,
    GLSL_DATA_TYPE_UNSIGNED_SHORT
};